USE [master]
GO

/****** Object:  Database [Hej_Omra]    Script Date: 8/17/2022 2:36:25 AM ******/
CREATE DATABASE [Hej_Omra]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Hej&Omra', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Hej&Omra.mdf' , SIZE = 24576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 8192KB )
 LOG ON 
( NAME = N'Hej&Omra_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Hej&Omra_log.ldf' , SIZE = 49152KB , MAXSIZE = 2048GB , FILEGROWTH = 8192KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hej_Omra].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Hej_Omra] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Hej_Omra] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Hej_Omra] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Hej_Omra] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Hej_Omra] SET ARITHABORT OFF 
GO

ALTER DATABASE [Hej_Omra] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Hej_Omra] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Hej_Omra] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Hej_Omra] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Hej_Omra] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Hej_Omra] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Hej_Omra] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Hej_Omra] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Hej_Omra] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Hej_Omra] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Hej_Omra] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Hej_Omra] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Hej_Omra] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Hej_Omra] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Hej_Omra] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Hej_Omra] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Hej_Omra] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Hej_Omra] SET RECOVERY FULL 
GO

ALTER DATABASE [Hej_Omra] SET  MULTI_USER 
GO

ALTER DATABASE [Hej_Omra] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Hej_Omra] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Hej_Omra] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Hej_Omra] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Hej_Omra] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Hej_Omra] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Hej_Omra] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Hej_Omra] SET  READ_WRITE 
GO

